### ISSUE TITLE
Investigate why all Nazareth news items from their RSS feed have been posted again

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1003]
Let's investigate if it's our fault or the fault of the content of the rss feed.

**Comment by lucasvanhalst** [comment]
Issue is that the 'url' property of their rss feed changed from https://www.nazareth.be/het-maaiseizoen-is-begonnen to https://nazareth.be/het-maaiseizoen-is-begonnen (th `www.` is removed). We should change the scraper so that it uses the `guid` property instead of the url, because if the url changes because they changed the article title or whatever there will also be made a new news item
