### ISSUE TITLE
Regional news: tooltip is flashing when hovering over city 'Heers'

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1058]
The tooltip appears and disappears all the time. Maybe we should increase the map's bottom margin?

<img width="835" alt="screen shot 2018-08-10 at 10 04 33" src="https://user-images.githubusercontent.com/17762105/43946173-cf4379cc-9c84-11e8-8204-7c4bbe355ba0.png">

**Comment by abom** [comment]
This seems to be a [known problem](https://github.com/neveldo/jQuery-Mapael/issues/361) (tested with other maps too), as suggested, i [just allowed clicking ](https://github.com/our-city-app/oca-backend/pull/1072/commits/8721896d0e8e6e9d2b5a442637455951b409db7b)the city even if the tooltip is covering it, until the problem is resolved.
