### ISSUE TITLE
First time setup script

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#110]
Create a setup script that runs when the server starts up for the first  time in a dev environment so you don't have to manually create a lot of things.

1. dependencies
  * python 2.7
  * python jpeg encoder
  * `sudo apt-get install libxml2-dev libxslt1-dev python-dev`
  * `pip install -r rogerthat-backend/requirements.txt`
  * latest LTS node
  * gulp + bower global
  * npm install
2. server settings
3. oca server settings
4. set default chat background
5. create 5 apps (rogerthat, 2 locals, one 'foreign' and osa-loyalty)
6. Save and publish JS embeddings
7. Setup the so-called app circles for the local apps
8. Create some default dashboard news items (the items you see when opening a dashboard, not the news in apps)
9. create 2 legal entities: mobicage and a random "foreign" one
10. create 2 regio manager teams, one for each legal entity. 
  * assign the mobicage team to the local apps
  * assign the other app to the foreign regio manager team
11. create a regio manager in each team who is a support manager
12. execute the function `add_all_products`
13. For each app:
  * run a limited 'prospect find' search so there are some prospects in each app
  * create a service which has the 'city app' module and the other expected modules
  * Create 3 other services with a descriptive name (e.g. pharmacy in xxx app, butcher in yyy app) with expected modules
  * Add a default terminal slide

Also ensure there are enough watchers for the build script on *nix `echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

last but not least provide a readme with instructions to run the script.

**Comment by bart-at-mobicage** [comment]
@abom, to run rogerthat in development mode on your local laptop:

* install the system/python dependencies described in step 1
* ask me, Ruben or Lucas to send you this file: https://drive.google.com/open?id=0B-N41qL7ZCzxeEVsazBWRFphdTQ
  * it can only be accessed by someone of Mobicage, because it contains secret information
  * unzip it in ~/tmp
  * this database contains step 2-11
* clone git@github.com:rogerthat-platform/rogerthat-backend.git
* clone git@github.com:our-city-app/oca-backend.git
* execute: 
```
cd oca-backend
python build.py
./start_rogerthat.sh
````
* go to http://localhost:8080/mobiadmin/settings and change 10.1.1.105 (my ip) into your localhost (or your ip)

Now you should be able to access
* the shop (aka Business Admin) at http://localhost:8080/internal/shop
* rogerthat web version at http://localhost:8080

For this task:
* create a new URL handler on /admin/home/dev_init
  * add it to oca-backend/main_admin.py, only if DEBUG=True
  * create the initial models programmatically. you can always have a look at http://localhost:8000/datastore to see the models
    * step 2. --> see the ServerSettings model, but don't include our secrets/or and signatures, they do not belong in a public repository
    * step 3. --> see the SolutionServerSettings model, but don't include our secrets and/or signatures, they do not belong in a public repository
    * step 4. --> ChatBackgroundImage (this file need to be uploaded into the blobstore: https://drive.google.com/file/d/0B-N41qL7ZCzxakF1cnEtejhrNXc/view?usp=sharing)
    * step 5. --> App
    * step 6. --> App.orderable_app_ids
    * step 7. --> can be skipped
    * step 8. --> LegalEntity
    * step 9. --> RegioManagerTeam
    * step 10. --> RegioManager
    * step 11. you can search for the `add_all_products` method in the code and just execute it
    * step 12. --> ShopApp. (Might take us too far to automate or maybe we can hardcode it for be-loc, TBD)
