### ISSUE TITLE
Add extra payment type in dashboard shop: Payconiq

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1135]
Next to creditcard, we want to give the customers the option to pay with Payconiq. Let's investigate and work it out in a github issue.

Would it be easier to integrate payconiq in our dashboard, like we did with Stripe? Or shall we generate a rogerthat QR code which starts a local flow with the pay widget? This way we could reuse the existing app2app integration.

Info about payconiq web integration, see https://dev.payconiq.com/online-payments-dock/#payconiq-online-widget or https://dev.payconiq.com/online-payments-dock/#payconiq-online-custom-online.

We have a test merchant id and api keys etc.
I'll contact payconiq for a production merchant id for OSA and the contracts with our bank.

**Comment by lucasvanhalst** [comment]
Should be fairly straightforward using their widget.

There's an example for generating the signature needed for the widget here: https://github.com/payconiq/python_signature/blob/master/signature_validation_python/api.py

Instead of the current "Pay with creditcard" button in the customer store, we need to change it to "next" which brings them to a new page showing the payment options. For belgium this will be payconiq and credit card, for others only credit card. This information should come from the server (perhaps in the same call that we fetch the store products).
After they've chosen one of the options we can continue / finish the payment.

So it goes as follows
- Choose products in shop 
- choose payment method -> choose payconiq
- When VAT is not filled in, ask for it in a textbox. info text: "Om een correcte factuur te kunnen opmaken, gelieve uw BTW nummer in te vullen. Indien u niet BTW-plichtig bent mag u dit overslaan."
- request to server to get transaction signature. We probably need to save this info in the datastore too, not sure
- load payconiq widget (with signature & other info like merchant id from server)
- payconiq does its magic (pay via the payconiq app using a qr code)
- our server receives a webhook with a status update about the transaction. Execute the `pay_order` method, but be sure we don't charge the credit card. Also ensure the invoice is still created and set to 'paid' immediately.
- the widget also receives the result, use this to complete the flow.

**Comment by lucasvanhalst** [comment]
Currently blocked for testing, we need a new JWT for our test account, the old one expired on 2 october
