### ISSUE TITLE
re-index customer when service is disabled

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#372]
See https://github.com/our-city-app/oca-backend/pull/365

> A small note for the customer search, when disabling or enabling a service, the search index still contain the old data (last indexing), so the service can be disabled (has no app_id on the actual datastore Customer record), but it's listed when searching the index.
> 
> I think the customer should be re-indexed after the service is enabled or disabled.

**Comment by abom** [comment]
After re-indexing, the problem is not resolved, because when a customer is indexed, the default service identity **appIds** is used to set the index document **app_ids**, and this property of service identity is not changed whether the service is disabled or not.

For now i just filter out the disabled services from search results (Dashboard).
