### ISSUE TITLE
different news-streams

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#492]
The news-stream functionality gets overloaded in big cities.
(look @ Sint-truiden)

The city news gets snowed down by all the merchants promotions.
We will not be able to have happy customers in this way when we start in cities above 40.000 inhabitants.

We should have different news-streams.
City-news
Promotions
Jobs
Activities/tourisme

**Comment by RubenMattan** [comment]
### Specs

#### Sections
News items will have a new property 'Label' by default this will be 'None', but we can set this to 'Jobs'.

The client will have 2 sidebar items, 'News' and 'Jobs' instead of just 'News' all news items will be filtered on the corresponding label. So 'Jobs' items will not be shown in the 'News' view.

#### City-news
Will have the highest priority by default
