### ISSUE TITLE
Service does not get buttons to approve or decline in osa-demo-3 app during registration

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#570]
![schermafbeelding 2017-09-29 om 13 50 40](https://user-images.githubusercontent.com/26439611/31016948-0c7b976c-a527-11e7-8bc7-e8cfd8eaeede.png)

**Comment by abom** [comment]
The city app module needs to be enabled for this service (it's enabled for another one now).

**Comment by RubenMattan** [comment]
@stevendepaepe does this answer your issue?

**Comment by bart-at-mobicage** [comment]
was misconfiguration in osa-demo-3. 
"bart testcustomer" is the main service of osa-demo-3 (that's why this services received that inbox message) but didnt have the CITY_APP module.

I removed CITY_APP from the test "Stad Halle" service (because there can only be 1 service with CITY_APP) and added it to bart testcustomer
