### ISSUE TITLE
AGENDA - UIT IN VLAANDEREN

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#614]
It seems that the Secret en the Key doesn't do the work they should do.
After 4 days their are no events in the agenda of the city Lo-Reninge.

When we check the dashboard it looks like the Key&Secret are well configured.

First demo's will be next week so this is urgent

![schermafbeelding 2017-10-18 om 08 47 09](https://user-images.githubusercontent.com/23034120/31704368-3f86c8b6-b3e1-11e7-94c7-8896b997d6ba.png)

**Comment by bart-at-mobicage** [comment]
Quickly investigated. The UiT API returned only 4 events. All 4 are skipped because they don't have a start time.

- https://www.uitinvlaanderen.be/agenda/e/op-zoek-naar-het-gouden-koekje/f1bcb16c-35c6-4e1b-a07b-a3cd2481d932
- https://www.uitinvlaanderen.be/agenda/e/duiventoren-lo-reninge/A1686162-BC77-E6CF-BD84977A63844236
- https://www.uitinvlaanderen.be/agenda/e/met-jaek-en-nink-door-het-vlakke-land/7fa3f2bf-a684-441a-bf5e-7c4887dece77
- https://www.uitinvlaanderen.be/agenda/e/bezoekerscentrum-jules-destrooper/1a5ba75d-62e5-4992-8d87-441ac66d3fd7

**Comment by RubenMattan** [comment]
We only fetch events for 'lo-reninge' but the list show events from 'lo', 'reninge', 'Pollinkhove'

**Comment by RubenMattan** [comment]
Combined there are 13 events, the rest have no date or are recurring

**Comment by RubenMattan** [comment]
?q=city:lo-reninge
=>
?q=city:lo-reninge OR city:lo OR city:reninge OR city:Pollinkhove

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/619
