### ISSUE TITLE
error : Please enter a valid url 

### ISSUE THREAD

**Issue by samyongo** [our-city-app/oca-backend#709]
Hi,

**I m trying to set up the link below:**

https://payment.appcorner.cd/api/paynow_image?article_id=12345&article_name=Laptop Asus&payment_amount=450&status=0&currency=USD

**on the page below**

![img_1768](https://user-images.githubusercontent.com/26000733/34453845-4df08c3c-ed5e-11e7-81e9-cd5cefe6413f.jpg)

and I m getting the error please enter a valid url

Please help because the API is ready and it's just this part that is the blocking point.

Thanks,

Sam Yongo

**Comment by bart-at-mobicage** [comment]
Hi Sam,

If you replace the space between "Laptop" and "Asus" by %20, then the URL will be valid. As you can see, Github didn't treat it as a valid URL either, because not whole the URL is colored in blue.

--> https://payment.appcorner.cd/api/paynow_image?article_id=12345&article_name=Laptop%20Asus&payment_amount=450&status=0&currency=USD

**Comment by samyongo** [comment]
Dear Bart,

Thank you very much, it worked.

Regard,

Sam Yongo
