### ISSUE TITLE
Lo-reninge QR codes are missing in inbox

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#755]
Bij bv. BD Technix en The Beautybar zijn er geen QR codes bij Instellingen Postvak in.

At BD Technix and The Beautybar there are no QR codes at Settings Inbox.

![schermafbeelding 2018-02-23 om 15 14 52](https://user-images.githubusercontent.com/33022464/36598600-04b19410-18ad-11e8-98ad-0b4a75f692d0.png)

**Comment by bart-at-mobicage** [comment]
@abom, can you check what's the display logic of this QR code?

**Comment by abom** [comment]
The qr code would be displayed if solution settings has a inbox_connector_qrcode.
I checked the service of **BD Technix**, and it's None.

**Comment by abom** [comment]
It can be reproduced locally, i think it's the same transaction problem when saving solution settings.

**Comment by abom** [comment]
Locally, it happens only for newly created services.

**Comment by abom** [comment]
The cause of the problem is that sln_settings returned from bizz.provision function is saved (with its old state) again [here](https://github.com/our-city-app/oca-backend/blob/master/src/solutions/common/bizz/__init__.py#L641) and [here](https://github.com/our-city-app/oca-backend/blob/master/src/solutions/common/bizz/__init__.py#L663), so it overwrites any changes done during the [configuration of inbox qr code](https://github.com/our-city-app/oca-backend/blob/master/src/solutions/common/bizz/provisioning.py#L1100).

So, we cannot do **model.get()** outside a transaction, then use this state of an entity to store/put it later, this might introduce data corruptions at the end.
Keeping in mind that in an _uber/propagated transaction_, doing model.get() will return the state before starting the transaction, so any inner transaction would just overwrite the data of the outer transactions, as they now are 1 transaction that's committed once.
