### ISSUE TITLE
GDPR: Newsletters

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#865]
Next to the GDPR related email that we'll send in the beginning of May, marketing emails will be sent to inform users of our new features: Regional news, Joyn, Payconiq, ...
In the emails, we'll ask the user's permission to keep him up to date with emails with news. There will be a button that should link to an unauthenticated request handler in OCA. OCA should save this setting somewhere.

The customer export should include the user's permission to send emails (such that we can hide the GDPR part if the user already granted us permission)

- [ ] Add 2 columns to the customer export: `confirmation URL` and `confirmed`
- [ ] Create a RequestHandler that stores the confirmation and show a success message. Let's use the style of the customer signup page.
  - Store it in the datastore

![screen shot 2018-05-03 at 10 27 22](https://user-images.githubusercontent.com/17762105/39566709-cc9243ae-4ebc-11e8-8d1b-4607b75f7d27.png)

**Comment by RubenMattan** [comment]
I suppose we need to ask permission before sending an email instead of sending emails to ask permission...

**Comment by bart-at-mobicage** [comment]
> I suppose we need to ask permission before sending an email instead of sending emails to ask permission...

Right now, we are still allowed to do this. After May 25th we aren't

**Comment by RubenMattan** [comment]
Yes i know but like its described right now we are violating GDPR. 
We should add a checkbox in the customer signup.

**Comment by RubenMattan** [comment]
https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations/legal-grounds-processing-data/grounds-processing/does-consent-given-25-may-2018-continue-be-valid-once-gdpr-starts-apply-25-may-2018_en

**Comment by RubenMattan** [comment]
just had a look at our marketing tool and suggest to do the following.

When customers register we add a checkbox if they want to receive marketing updates otherwise we won't send a smart email.
Create and use 1 list (marketing newsletter) for all our customers, when sending a smart email make sure to add that recipient to the list as well. 
Then for that 1 list we create a webhook to add/remove consent to that list

Still need to validate with legal if we need to add a way to unsubscribe/subscribe in the dashboard as well

https://www.campaignmonitor.com/api/transactional/#smart-email-listing
https://www.campaignmonitor.com/api/lists/#list-webhooks
https://www.campaignmonitor.com/api/webhooks/#whats-a-webhook
