### ISSUE TITLE
RSS news Nazareth

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#958]
Nazareth reports that there are no push notifications anymore when a news item is sent. They reported this a while ago, then we introduced a "push notifications" checkbox. This resolved the problem back then, but now there are no push notification anymore. Because of regional news?

**Comment by lucasvanhalst** [comment]
according to this:
https://github.com/rogerthat-platform/rogerthat-android-client/blob/76917e9c58191d119ff4b2a8e589b40cb56c1cc2/rogerthat/src/main/java/com/mobicage/rogerthat/util/consent/ConsentProvider.java#L62

No consent is asked unless it was stored as 'true' in the config provider. But that will only be the case when the settings have been updated. But, the settings should've been updated when the user accepted our terms of use, so I'm not sure how this could've happened. Still, those consent settings should probably be 'true' by default instead of false.
